### ISSUE TITLE
Slider LED drivers

### ISSUE THREAD

**Issue by pjbulls** [jakplugg/Typhoon#13]
I'm trying to understand the choice in the op-amps used for the slider LED drivers (TLV2172)? It seems like a much cheaper one could be used, no need for rail-to-rail output or high slew rate.

Furthermore, there's just the LED in the feedback path, but nothing can go the other way. Could this not damage the LED if you apply a high (negative) CV? Might it be safer to connect a diode of opposite polarity in parallel with the slider LEDs?

**Comment by jakplugg** [comment]
You can use TL072, that is a mistake, sorry! as for damaging the LED, i have not heard of that happening, mutable instruments uses the LED in the op amp feedback as well. You can also put bipolar red/green LEDs in the sliders and they indicate polarity with color.

**Comment by pjbulls** [comment]
Great, thanks for confirming! Bipolar slider LEDs sound lovely but I've never been able to find any 😄 

e: Bivar R3BC seems like the ones to get but they are _expensive_ 😢

**Comment by jakplugg** [comment]
Just a note, You can use round 3mm LEDs on the sliders if they don't have a flange.
