### ISSUE TITLE
Panel

### ISSUE THREAD

**Issue by TotalRefusal** [jakplugg/Typhoon#2]
Hi! Not sure, but "TIME" and "BANK" seems to be wrong way, either on panel, or on pcb :) Cheers!

**Comment by TotalRefusal** [comment]
> 
> 
> Hi! Not sure, but "TIME" and "BANK" seems to be wrong way, either on panel, or on pcb :) Cheers!

Took a look @schematics - seems the panel to be wrong way. BANK is left and TIME is right :)

**Comment by dlavila** [comment]
why is this closed if the panel was not fixed?
