### ISSUE TITLE
Lack of end user documentation

### ISSUE THREAD

**Issue by baderbuddy** [jakplugg/Typhoon#9]
I noticed that there's a lack of user documentation for this module. I recently bought one of these and have been doing research about how to use it. I think I probably have enough information at this point to start putting something together but before I do I wanted to see if a PR for that would be something that's accepted/welcomed or not.

**Comment by jakplugg** [comment]
Sorry i missed this, the module is basically the same thing as "microcell" but with a different layout. the function is the same though.
